project:
  name: freelycar_saas
# 开发环境配置
server:
  port: 8080
spring:
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://192.168.0.167:3306/${project.name}?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  path: ${project.name}-log
  level:
    root: info
    org:
      springframework:
        web: info
        security: info
      hibernate: info

swagger:
  enable: true

# 自定义的上传路径和映射路径参数
upload:
  picture:
    path: /Users/tangwei/upload
    url: http://freelycar.cn/upload