project:
  name: freelycar_saas
# 生产环境配置
server:
  port: 8080
spring:
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://www.pwai.net.cn:3306/${project.name}?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: ymq920907

logging:
  path: ${project.name}-log
  level:
    root: error
    org:
      springframework:
        web: error
        security: error
      hibernate: error