spring:
  # 选择加载不同环境的配置文件
  profiles:
    active: test
    include: data,mvc,endpoints

  # 静态资源路径
  #  resources:
  #    static-locations: classpath:[static/],context:/

  # 配置热部署
  devtools:
    livereload:
      enabled: false #是否支持livereload
      port: 35729
    restart:
      # 如果改为true则当修改java目录下的文件时会自动进行重启
      enabled: false
      additional-paths: src/main/java

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL55Dialect
    open-in-view: true
  output:
    ansi:
      enabled: always

leancloud:
  app:
    id: YPVPvcghD0yT1CtQKUOpOUGI-gzGzoHsz
    key: AnrwmLo01qL7RuKNbV0NwWR4
  url:
    res: https://leancloud.cn/1.1/requestSmsCode
    ver: https://leancloud.cn/1.1/verifySmsCode

baidu:
  map:
    ak: d9lPgxKkEwRlEoguEGEmjb0MweNqYk2G
    geocoding:
      url: http://api.map.baidu.com/geocoding/v3/
      reverse:
        url: http://api.map.baidu.com/reverse_geocoding/v3/

edaijia:
  order: https://baoyang.d.edaijia.cn/api/third/2/order/
  channel: 91
  customerId: CH0110000223
