project:
  name: freelycar_saas
# 生产环境配置
server:
  port: 8080
spring:
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://www.freelycar.com:3306/${project.name}?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: freelycar2016
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  path: ${project.name}-log
  level:
    root: info
    org:
      springframework:
        web: info
        security: info
      hibernate: error

swagger:
  enable: true

upload:
  picture:
    path: C:\nginx\html\upload\storeimg
    url: https://freelycar.com/upload/storeimg/