#spring:
#  endpoints:
#    shutdown:
#      enabled: true
#      path: /xxx
#  management:
#    security:
#      enabled: true
#    port: 9001
#    address: 127.0.0.1
#    context-path: /admin
#  security:
#    basic:
#      enabled: true
#      path: /admin
#    user:
#      name: root
#      password: 123456