spring:
  # 选择加载不同环境的配置文件
  profiles:
    active: dev
    include: data

  # 静态资源路径
  #  resources:
  #    static-locations: classpath:static/,file:static/

  # 配置热部署
  devtools:
    restart:
      # 如果改为true则当修改java目录下的文件时会自动进行重启
      enabled: true
      additional-paths: src/main/java

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL55Dialect
  output:
    ansi:
      enabled: always

logging:
  path: ${project.name}-log
  level:
    root: debug
    org:
      springframework:
        web: debug
        security: info
      hibernate: info


#package:
#    type: war
