spring:
  # 选择加载不同环境的配置文件
  profiles:
    active: pro
    include: data,mvc

  # 静态资源路径
  #  resources:
  #    static-locations: classpath:[static/],context:/

  # 配置热部署
  devtools:
    livereload:
      enabled: true #是否支持livereload
      port: 35729
    restart:
      # 如果改为true则当修改java目录下的文件时会自动进行重启
      enabled: false
      additional-paths: src/main/java

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL55Dialect
    open-in-view: true
  output:
    ansi:
      enabled: always
