
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: blog_admin
    password: 12345654321
    url: jdbc:mysql://121.36.48.165:3306/freelycar_saas?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/freelycar_saas?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        hbm2ddl:
          auto: update



server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
    max-threads: 200
    max-connections: 8192
